import { Flashcard } from './types.js';

export const SEED_FLASHCARDS: Flashcard[] = [
  // ============================================================
  // GATE CS / CS FOUNDATIONS: MODULE 1 - LINEAR DATA STRUCTURES
  // ============================================================
  {
    id: 'fc_arrays_01',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_dsa',
    lessonId: 'les_gate_dsa_arrays',
    conceptId: 'arrays',
    conceptName: 'Arrays & Memory Addressing',
    question: 'How is the memory address of element A[i] calculated in a 1D zero-indexed contiguous array with element size S?',
    answer: 'Address(A[i]) = BaseAddress + (i * S)',
    explanation: 'Because array elements are stored contiguously in memory, arbitrary element access is directly computed in O(1) time without traversing preceding elements.',
    type: 'Formula',
    difficulty: 'easy',
    sourceId: 'les_gate_dsa_arrays',
    sourceTitle: 'Linear Memory Layouts & Cache Locality',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_arrays_02',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_dsa',
    lessonId: 'les_gate_dsa_arrays',
    conceptId: 'arrays',
    conceptName: 'Arrays & Memory Addressing',
    question: 'Why does inserting or deleting an arbitrary element in an array take O(n) worst-case time?',
    answer: 'It requires shifting all subsequent (n - i - 1) elements to maintain physical contiguous order in memory.',
    explanation: 'Inserting at index 0 shifts all n elements right. While indexing is O(1), element relocation incurs O(n) data movement.',
    type: 'Conceptual',
    difficulty: 'easy',
    sourceId: 'les_gate_dsa_arrays',
    sourceTitle: 'Linear Memory Layouts & Cache Locality',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_linked_01',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_dsa',
    lessonId: 'les_gate_dsa_linked',
    conceptId: 'linked_lists',
    conceptName: 'Linked Lists & Pointer Mutation',
    question: 'What is the primary trade-off between Singly Linked Lists and Doubly Linked Lists?',
    answer: 'Doubly Linked Lists support O(1) predecessor deletion and bidirectional traversal, but require an extra pointer per node (memory overhead).',
    explanation: 'A singly linked list cannot delete a node in O(1) given only a pointer to that node without having a reference to the preceding node or copying data.',
    type: 'Comparison',
    difficulty: 'medium',
    sourceId: 'les_gate_dsa_linked',
    sourceTitle: 'Pointer Mutation & Dynamic Chains',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_linked_02',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_dsa',
    lessonId: 'les_gate_dsa_linked',
    conceptId: 'linked_lists',
    conceptName: 'Linked Lists & Pointer Mutation',
    question: 'How does Floyd\'s Cycle-Finding Algorithm (Tortoise and Hare) detect a loop in a linked list in O(n) time and O(1) space?',
    answer: 'By advancing a slow pointer by 1 step and a fast pointer by 2 steps. If a cycle exists, they must collide inside the loop.',
    explanation: 'Relative distance between the two pointers decreases by 1 in each cycle iteration, guaranteeing a collision within the loop without extra memory.',
    type: 'Application',
    difficulty: 'hard',
    sourceId: 'les_gate_dsa_linked',
    sourceTitle: 'Pointer Mutation & Dynamic Chains',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_stacks_01',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_dsa',
    lessonId: 'les_cs_stacks',
    conceptId: 'stacks',
    conceptName: 'Stacks & LIFO Operations',
    question: 'Which principle governs the order of operations in a Stack data structure?',
    answer: 'LIFO (Last-In, First-Out): The most recently inserted element is the first one removed.',
    explanation: 'Both push and pop operate exclusively on the top pointer in O(1) time.',
    type: 'Definition',
    difficulty: 'easy',
    sourceId: 'les_cs_stacks',
    sourceTitle: 'Stack Execution & Monotonic Invariants',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_stacks_02',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_dsa',
    lessonId: 'les_cs_stacks',
    conceptId: 'stacks',
    conceptName: 'Stacks & LIFO Operations',
    question: 'How does a monotonic decreasing stack find the Next Greater Element for all items in an array in O(n) total time?',
    answer: 'Each element is pushed once and popped at most once when a strictly greater element arrives.',
    explanation: 'Because every element undergoes at most 1 push and 1 pop throughout the entire traversal, the amortized runtime is O(n), not O(n^2).',
    type: 'Application',
    difficulty: 'hard',
    sourceId: 'les_cs_stacks',
    sourceTitle: 'Stack Execution & Monotonic Invariants',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_queues_01',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_dsa',
    lessonId: 'les_cs_queues',
    conceptId: 'queues',
    conceptName: 'Queues & Circular Buffers',
    question: 'How does a circular queue avoid false overflow when elements have been dequeued?',
    answer: 'By computing (rear + 1) % Capacity to wrap indices around to the front of the underlying fixed array.',
    explanation: 'In a naive array queue, dequeue advances the front pointer, stranding unused cells at the start. Modulo indexing reuses freed cells.',
    type: 'Formula',
    difficulty: 'medium',
    sourceId: 'les_cs_queues',
    sourceTitle: 'FIFO Buffers & Circular Queues',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_trees_01',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_dsa',
    lessonId: 'les_cs_trees',
    conceptId: 'trees',
    conceptName: 'Binary Trees & Traversals',
    question: 'Which tree traversal yields the sorted order of values in a Binary Search Tree (BST)?',
    answer: 'In-order Traversal (Left Subtree -> Root -> Right Subtree)',
    explanation: 'By the BST invariant, all nodes in the left subtree are smaller than the root, and all in the right subtree are greater. In-order visits them in ascending order.',
    type: 'Conceptual',
    difficulty: 'easy',
    sourceId: 'les_cs_trees',
    sourceTitle: 'Recursive Trees & Hierarchical Structures',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_bst_01',
    subjectId: 'cs_foundations',
    moduleId: 'mod_cs_3',
    lessonId: 'les_cs_bst',
    conceptId: 'bst',
    conceptName: 'Binary Search Trees (BST)',
    question: 'What is the worst-case search complexity of an un-balanced BST with n nodes, and when does it occur?',
    answer: 'O(n) time, which occurs when elements are inserted in already-sorted or reverse-sorted order, degenerating the tree into a linked list.',
    explanation: 'Balanced search trees (like AVL or Red-Black trees) guarantee O(log n) height by performing tree rotations.',
    type: 'Recall',
    difficulty: 'medium',
    sourceId: 'les_cs_bst',
    sourceTitle: 'Binary Search Tree Operations & Invariants',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_recursion_01',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_algo',
    lessonId: 'les_gate_algo_paradigm',
    conceptId: 'recursion',
    conceptName: 'Recursion & Induction',
    question: 'What two fundamental components are mandatory in every recursive algorithm?',
    answer: '1. Base Case (halting condition) and 2. Recursive Step (reducing the problem toward the base case).',
    explanation: 'Without a properly reachable base case, recursive calls continue indefinitely until stack overflow occurs.',
    type: 'Definition',
    difficulty: 'easy',
    sourceId: 'les_gate_algo_paradigm',
    sourceTitle: 'Divide and Conquer & Master Theorem',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_hashing_01',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_dsa',
    lessonId: 'les_gate_dsa_arrays',
    conceptId: 'hashing',
    conceptName: 'Hashing & Hash Tables',
    question: 'What is the load factor (alpha) of a hash table with n keys and m slots, and what does it measure?',
    answer: 'alpha = n / m. It measures the average number of elements stored per bucket slot.',
    explanation: 'When alpha exceeds a set threshold (typically 0.75 for open addressing), the table is rehashed to a larger array to preserve O(1) expected lookup.',
    type: 'Formula',
    difficulty: 'medium',
    sourceId: 'les_gate_dsa_arrays',
    sourceTitle: 'Hash Tables & Collision Resolution',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_toc_01',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_theory',
    lessonId: 'les_gate_toc_dfa',
    conceptId: 'gate_toc',
    conceptName: 'Theory of Computation & Automata',
    question: 'What formal language class is recognized by a Deterministic Finite Automaton (DFA)?',
    answer: 'Regular Languages (Type-3 in the Chomsky Hierarchy).',
    explanation: 'DFAs possess finite memory and cannot recognize non-regular languages such as {a^n b^n | n >= 0} which require unbounded counting (Pushdown Automata).',
    type: 'Definition',
    difficulty: 'easy',
    sourceId: 'les_gate_toc_dfa',
    sourceTitle: 'Finite Automata & Pumping Lemma',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_toc_02',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_theory',
    lessonId: 'les_gate_toc_dfa',
    conceptId: 'gate_toc',
    conceptName: 'Theory of Computation & Automata',
    question: 'What is the Pumping Lemma for regular languages used for in formal proofs?',
    answer: 'It is a property that all regular languages must satisfy, used primarily as a proof by contradiction to prove a language is NOT regular.',
    explanation: 'If a language violates any condition of the Pumping Lemma (xyz conditions where |xy| <= p and y != epsilon), it cannot be regular.',
    type: 'Conceptual',
    difficulty: 'hard',
    sourceId: 'les_gate_toc_dfa',
    sourceTitle: 'Finite Automata & Pumping Lemma',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_compiler_01',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_theory',
    lessonId: 'les_gate_compiler_parsing',
    conceptId: 'gate_compiler',
    conceptName: 'Compiler Design & Syntax Analysis',
    question: 'Why must left-recursion be eliminated from context-free grammars for Top-Down (LL) Parsers?',
    answer: 'Because left-recursive productions cause recursive descent parsers to loop infinitely without consuming any input tokens.',
    explanation: 'An A -> A alpha production tries to parse non-terminal A before advancing the input stream, generating infinite recursion.',
    type: 'Conceptual',
    difficulty: 'medium',
    sourceId: 'les_gate_compiler_parsing',
    sourceTitle: 'Lexical Analysis & Parsing Algorithms',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_os_01',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_systems',
    lessonId: 'les_gate_os_sync',
    conceptId: 'gate_os',
    conceptName: 'Operating Systems & Concurrency',
    question: 'What are the four Coffman conditions necessary and sufficient for a deadlock to occur?',
    answer: '1. Mutual Exclusion, 2. Hold and Wait, 3. No Preemption, 4. Circular Wait.',
    explanation: 'Invalidating any single one of these four conditions is sufficient to prevent deadlocks in an operating system.',
    type: 'Recall',
    difficulty: 'medium',
    sourceId: 'les_gate_os_sync',
    sourceTitle: 'Process Synchronization & Virtual Memory',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_os_02',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_systems',
    lessonId: 'les_gate_os_sync',
    conceptId: 'gate_os',
    conceptName: 'Operating Systems & Concurrency',
    question: 'What is the role of the Translation Lookaside Buffer (TLB) in paged virtual memory?',
    answer: 'It acts as an associative hardware cache for page table entries to avoid the memory penalty of two physical accesses per instruction.',
    explanation: 'A TLB hit translates virtual page number to physical frame number in 1 clock cycle, avoiding traversing multi-level page tables in DRAM.',
    type: 'Conceptual',
    difficulty: 'hard',
    sourceId: 'les_gate_os_sync',
    sourceTitle: 'Process Synchronization & Virtual Memory',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_dbms_01',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_systems',
    lessonId: 'les_gate_dbms_norm',
    conceptId: 'gate_dbms',
    conceptName: 'Database Management Systems (DBMS)',
    question: 'What defines Boyce-Codd Normal Form (BCNF) in relational databases?',
    answer: 'For every non-trivial functional dependency X -> Y, X must be a superkey of the relation.',
    explanation: 'BCNF eliminates all redundancy arising from functional dependencies and is strictly stronger than 3NF.',
    type: 'Definition',
    difficulty: 'medium',
    sourceId: 'les_gate_dbms_norm',
    sourceTitle: 'Normalization & Transaction ACID Properties',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_net_01',
    subjectId: 'gate_cs',
    moduleId: 'mod_gate_systems',
    lessonId: 'les_gate_net_tcp',
    conceptId: 'gate_networks',
    conceptName: 'Computer Networks & TCP/IP',
    question: 'How does TCP achieve reliable byte-stream transmission over an unreliable IP network?',
    answer: 'Through sequence numbers, cumulative acknowledgments, retransmission timers, and sliding window flow/congestion control.',
    explanation: 'TCP detects lost segments via duplicate ACKs (Fast Retransmit) or timeout, and retransmits while throttling transmission rate via congestion windows.',
    type: 'Conceptual',
    difficulty: 'medium',
    sourceId: 'les_gate_net_tcp',
    sourceTitle: 'TCP Congestion Control & Routing Protocols',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },

  // ============================================================
  // UPSC CIVIL SERVICES / POLITY FLASHCARDS
  // ============================================================
  {
    id: 'fc_upsc_polity_01',
    subjectId: 'upsc_civil',
    moduleId: 'mod_upsc_polity',
    lessonId: 'les_upsc_preamble',
    conceptId: 'upsc_polity_constitution',
    conceptName: 'Indian Constitution & Basic Structure',
    question: 'Which landmark Supreme Court judgment established the Basic Structure Doctrine in Indian Constitutional Law?',
    answer: 'Kesavananda Bharati v. State of Kerala (1973)',
    explanation: 'The 13-judge bench held that while Parliament has wide amending powers under Article 368, it cannot alter or destroy the basic structure of the Constitution.',
    type: 'Recall',
    difficulty: 'easy',
    sourceId: 'les_upsc_preamble',
    sourceTitle: 'Constitutional Philosophy & Basic Structure',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_upsc_polity_02',
    subjectId: 'upsc_civil',
    moduleId: 'mod_upsc_polity',
    lessonId: 'les_upsc_preamble',
    conceptId: 'upsc_polity_constitution',
    conceptName: 'Indian Constitution & Basic Structure',
    question: 'What is the constitutional distinction between Fundamental Rights (Part III) and Directive Principles of State Policy (Part IV)?',
    answer: 'Fundamental Rights are legally enforceable (justiciable) in courts under Article 32/226, while Directive Principles are non-justiciable guiding principles for governance.',
    explanation: 'In Minerva Mills (1980), the Supreme Court noted the Constitution is founded on the bedrock of balance between Part III and Part IV.',
    type: 'Comparison',
    difficulty: 'medium',
    sourceId: 'les_upsc_preamble',
    sourceTitle: 'Constitutional Philosophy & Basic Structure',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },

  // ============================================================
  // CBSE CLASS 10 STEM: GENETICS & CELL BIOLOGY
  // ============================================================
  {
    id: 'fc_cbse_genetics_01',
    subjectId: 'school_stem',
    moduleId: 'mod_cbse_bio',
    lessonId: 'les_cbse_genetics',
    conceptId: 'school_cell_genetics',
    conceptName: 'Cell Division & Mendelian Genetics',
    question: 'What phenotypic ratio is obtained in the F2 generation of a classic Mendelian monohybrid cross between heterozygous individuals (Tt x Tt)?',
    answer: '3 : 1 (3 Dominant : 1 Recessive) phenotypic ratio, and 1 : 2 : 1 (1 TT : 2 Tt : 1 tt) genotypic ratio.',
    explanation: 'Mendel\'s Law of Segregation explains that allele pairs separate during gamete formation and randomly unite at fertilization.',
    type: 'Recall',
    difficulty: 'easy',
    sourceId: 'les_cbse_genetics',
    sourceTitle: 'Cell Division, Mitosis, Meiosis & Mendel\'s Laws',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_cbse_genetics_02',
    subjectId: 'school_stem',
    moduleId: 'mod_cbse_bio',
    lessonId: 'les_cbse_genetics',
    conceptId: 'school_cell_genetics',
    conceptName: 'Cell Division & Mendelian Genetics',
    question: 'How do chromosomes determine biological sex in human offspring?',
    answer: 'Females have homologous XX chromosomes, while males have XY. An egg always contributes X, while sperm contributes either X (female) or Y (male) with 50% probability.',
    explanation: 'Because the father\'s sperm carries either an X or Y chromosome, the biological sex is determined at fertilization by the male gamete.',
    type: 'Conceptual',
    difficulty: 'easy',
    sourceId: 'les_cbse_genetics',
    sourceTitle: 'Cell Division, Mitosis, Meiosis & Mendel\'s Laws',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },

  // ============================================================
  // COLLEGE DEGREE: DISTRIBUTED SYSTEMS & CONSENSUS
  // ============================================================
  {
    id: 'fc_college_dist_01',
    subjectId: 'college_eng',
    moduleId: 'mod_college_2',
    lessonId: 'les_college_dist',
    conceptId: 'college_distributed_sys',
    conceptName: 'Distributed Systems & Consensus',
    question: 'What does the CAP Theorem state regarding distributed systems?',
    answer: 'A distributed data store can simultaneously provide at most two out of three guarantees: Consistency, Availability, and Partition Tolerance.',
    explanation: 'When network partitions occur, distributed architectures must trade off between immediate responses (Availability) and linearizable consistency (Consistency).',
    type: 'Definition',
    difficulty: 'medium',
    sourceId: 'les_college_dist',
    sourceTitle: 'Distributed Systems, Consensus Protocols & CAP Theorem',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'fc_college_dist_02',
    subjectId: 'college_eng',
    moduleId: 'mod_college_2',
    lessonId: 'les_college_dist',
    conceptId: 'college_distributed_sys',
    conceptName: 'Distributed Systems & Consensus',
    question: 'In the Raft consensus algorithm, what purpose do terms and heartbeats serve?',
    answer: 'Terms act as logical clocks identifying stale leaders; periodic heartbeats suppress follower election timeouts to maintain cluster stability.',
    explanation: 'Raft guarantees safety in replicated state machines by electing exactly one leader per term and rejecting out-of-order log entries.',
    type: 'Formula',
    difficulty: 'hard',
    sourceId: 'les_college_dist',
    sourceTitle: 'Distributed Systems, Consensus Protocols & CAP Theorem',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
];
