import { Module, Lesson } from './types.js';

export const SEED_MODULES: Module[] = [
  // ==========================================
  // CS FOUNDATIONS
  // ==========================================
  {
    id: 'mod_cs_1',
    domainId: 'cs_foundations',
    code: 'CS-MOD-01',
    title: 'Linear Data Structures',
    description: 'Contiguous vs pointer-linked memory layouts, Big-O amortized analysis, and index access invariants.',
    order: 1,
    lessonIds: ['les_cs_arrays', 'les_cs_linked'],
    targetCompetency: 'Construct efficient contiguous buffers and pointer-linked chains with O(1) mutations.',
  },
  {
    id: 'mod_cs_2',
    domainId: 'cs_foundations',
    code: 'CS-MOD-02',
    title: 'Abstract Sequential Types',
    description: 'Restricted access sequential structures: LIFO stacks, execution call frames, and FIFO buffers.',
    order: 2,
    lessonIds: ['les_cs_stacks', 'les_cs_queues'],
    targetCompetency: 'Model call-stack evaluation, monotonic stacks, and breadth-first FIFO processing.',
  },
  {
    id: 'mod_cs_3',
    domainId: 'cs_foundations',
    code: 'CS-MOD-03',
    title: 'Hierarchical & Tree Structures',
    description: 'Recursive divide-and-conquer structures, binary trees, and binary search tree invariants.',
    order: 3,
    lessonIds: ['les_cs_trees', 'les_cs_bst'],
    targetCompetency: 'Implement tree traversals and maintain logarithmic search bounds.',
  },
  {
    id: 'mod_cs_4',
    domainId: 'cs_foundations',
    code: 'CS-MOD-04',
    title: 'Graph Theory & Networks',
    description: 'Adjacency models, BFS/DFS traversal, cycle detection, and connectivity invariants.',
    order: 4,
    lessonIds: ['les_cs_graphs'],
    targetCompetency: 'Traverse arbitrary topological graphs and identify shortest unweighted paths.',
  },
  {
    id: 'mod_cs_5',
    domainId: 'cs_foundations',
    code: 'CS-MOD-05',
    title: 'Searching & Hashing Algorithms',
    description: 'Logarithmic binary search invariants, hash distribution, and O(1) amortized map lookups.',
    order: 5,
    lessonIds: ['les_cs_search', 'les_cs_hash'],
    targetCompetency: 'Select optimal search and key-value hashing strategies under space-time constraints.',
  },

  // ==========================================
  // GATE CS & IT
  // ==========================================
  {
    id: 'mod_gate_1',
    domainId: 'gate_cs',
    code: 'GATE-MOD-01',
    title: 'Theoretical Computer Science & Compilers',
    description: 'Deterministic finite automata, regular expressions, Pumping Lemma, and parsing tables.',
    order: 1,
    lessonIds: ['les_gate_toc', 'les_gate_compiler'],
    targetCompetency: 'Evaluate language decidability and construct conflict-free grammar parsing tables.',
  },
  {
    id: 'mod_gate_2',
    domainId: 'gate_cs',
    code: 'GATE-MOD-02',
    title: 'Systems & Operating Kernels',
    description: 'Process synchronization, deadlock Coffman conditions, and network protocol stacks.',
    order: 2,
    lessonIds: ['les_gate_os', 'les_gate_networks'],
    targetCompetency: 'Solve resource allocation graphs, deadlock avoidance, and TCP congestion windows.',
  },
  {
    id: 'mod_gate_3',
    domainId: 'gate_cs',
    code: 'GATE-MOD-03',
    title: 'Database Management Systems',
    description: 'Relational algebra, functional dependencies, 3NF/BCNF normalization, and transaction ACIDity.',
    order: 3,
    lessonIds: ['les_gate_dbms'],
    targetCompetency: 'Design lossless-join, dependency-preserving BCNF relational database schemas.',
  },

  // ==========================================
  // UPSC CIVIL SERVICES
  // ==========================================
  {
    id: 'mod_upsc_1',
    domainId: 'upsc_civil',
    code: 'UPSC-MOD-01',
    title: 'Constitutional Governance & Rights',
    description: 'Constitutional supremacy, Article 368 amending power, Fundamental Rights, and DPSP synergy.',
    order: 1,
    lessonIds: ['les_upsc_const', 'les_upsc_rights', 'les_upsc_dpsp'],
    targetCompetency: 'Analyze constitutional articles, landmark Supreme Court rulings, and administrative law.',
  },
  {
    id: 'mod_upsc_2',
    domainId: 'upsc_civil',
    code: 'UPSC-MOD-02',
    title: 'Macroeconomics & Ecological Policy',
    description: 'Fiscal and monetary policies, GDP calculations, biodiversity conventions, and sustainable development.',
    order: 2,
    lessonIds: ['les_upsc_econ', 'les_upsc_env'],
    targetCompetency: 'Synthesize national economic growth initiatives with biodiversity preservation.',
  },

  // ==========================================
  // GENERAL SCHOOL STEM
  // ==========================================
  {
    id: 'mod_school_1',
    domainId: 'school_stem',
    code: 'STEM-MOD-01',
    title: 'Foundational Mechanics & Energy',
    description: 'Newtonian dynamics, inertia, free-body diagrams, and the Work-Energy Theorem.',
    order: 1,
    lessonIds: ['les_school_newton', 'les_school_energy'],
    targetCompetency: 'Apply F = ma and conservation of mechanical energy to multi-body constraint systems.',
  },
  {
    id: 'mod_school_2',
    domainId: 'school_stem',
    code: 'STEM-MOD-02',
    title: 'Calculus, Chemistry & Genetics',
    description: 'Derivatives as instantaneous rates of change, periodic trends, and Mendelian inheritance.',
    order: 2,
    lessonIds: ['les_school_table', 'les_school_calc', 'les_school_cell'],
    targetCompetency: 'Differentiate continuous polynomial functions and predict Mendelian gene ratios.',
  },

  // ==========================================
  // COLLEGE DEGREE SYLLABUS
  // ==========================================
  {
    id: 'mod_college_1',
    domainId: 'college_eng',
    code: 'ENG-MOD-01',
    title: 'Linear Algebra & Machine Learning',
    description: 'Vector spaces, matrix decomposition, eigenvalues, and gradient-descent optimization.',
    order: 1,
    lessonIds: ['les_college_la', 'les_college_ml'],
    targetCompetency: 'Formulate loss functions, compute matrix transformations, and tune hyperparameters.',
  },
  {
    id: 'mod_college_2',
    domainId: 'college_eng',
    code: 'ENG-MOD-02',
    title: 'Distributed Systems & Consensus',
    description: 'CAP theorem, network partitions, Paxos/Raft consensus, and eventual consistency.',
    order: 2,
    lessonIds: ['les_college_dist'],
    targetCompetency: 'Architect fault-tolerant distributed consensus topologies for mission-critical services.',
  },
];

export const SEED_LESSONS: Lesson[] = [
  // ==========================================
  // CS FOUNDATIONS LESSONS
  // ==========================================
  {
    id: 'les_cs_arrays',
    moduleId: 'mod_cs_1',
    domainId: 'cs_foundations',
    code: 'LES-CS-01',
    title: 'Arrays & Sequential Memory Layout',
    description: 'Explore contiguous memory allocation, address calculation formulas, CPU L1/L2 spatial locality, and dynamic array resizing amortized costs.',
    order: 1,
    estimatedMinutes: 25,
    learningObjectives: [
      'Calculate physical memory addresses using BaseAddress + i * sizeof(T)',
      'Analyze the difference between O(1) indexing and O(n) arbitrary insertion',
      'Explain CPU cache lines and spatial locality performance advantages',
    ],
    conceptIds: ['arrays'],
    prerequisiteConceptIds: [],
  },
  {
    id: 'les_cs_linked',
    moduleId: 'mod_cs_1',
    domainId: 'cs_foundations',
    code: 'LES-CS-02',
    title: 'Singly & Doubly Linked Pointer Chains',
    description: 'Dynamic non-contiguous nodes, pointer manipulation invariants, memory overhead per node, and pointer traversal traps.',
    order: 2,
    estimatedMinutes: 30,
    learningObjectives: [
      'Implement O(1) head insertion and node pointer rewiring',
      'Compare cache-miss overheads between contiguous arrays and linked lists',
      'Handle boundary conditions such as empty lists and single-node cycles',
    ],
    conceptIds: ['linked_lists'],
    prerequisiteConceptIds: ['arrays'],
  },
  {
    id: 'les_cs_stacks',
    moduleId: 'mod_cs_2',
    domainId: 'cs_foundations',
    code: 'LES-CS-03',
    title: 'LIFO Stacks & Execution Call Frames',
    description: 'Last-In-First-Out access discipline, hardware stack pointers, function call unwinding, and monotonic stack evaluation.',
    order: 1,
    estimatedMinutes: 25,
    learningObjectives: [
      'Model push, pop, and peek operations with strict O(1) time bounds',
      'Track call frame push and pop sequence during function execution',
      'Solve matching parenthesis and postfix expression evaluation problems',
    ],
    conceptIds: ['stacks'],
    prerequisiteConceptIds: ['arrays'],
  },
  {
    id: 'les_cs_queues',
    moduleId: 'mod_cs_2',
    domainId: 'cs_foundations',
    code: 'LES-CS-04',
    title: 'FIFO Queues & Circular Ring Buffers',
    description: 'First-In-First-Out processing, circular buffer modulo arithmetic, and double-ended queues for breadth-first scheduling.',
    order: 2,
    estimatedMinutes: 25,
    learningObjectives: [
      'Implement circular queue wrap-around via (rear + 1) % capacity',
      'Distinguish enqueue and dequeue invariants in producer-consumer pipelines',
      'Explain when queues prevent resource starvation in operating systems',
    ],
    conceptIds: ['queues'],
    prerequisiteConceptIds: ['linked_lists'],
  },
  {
    id: 'les_cs_trees',
    moduleId: 'mod_cs_3',
    domainId: 'cs_foundations',
    code: 'LES-CS-05',
    title: 'Recursive Tree Structures & Traversals',
    description: 'Inductive recursive structures, depth, height, pre-order, in-order, and post-order traversal call stacks.',
    order: 1,
    estimatedMinutes: 35,
    learningObjectives: [
      'Formulate structural induction for binary tree height and leaf counts',
      'Trace recursive stack frames for pre-order, in-order, and post-order traversals',
      'Calculate time and space complexity of tree recursion',
    ],
    conceptIds: ['recursion', 'trees'],
    prerequisiteConceptIds: ['stacks'],
  },
  {
    id: 'les_cs_bst',
    moduleId: 'mod_cs_3',
    domainId: 'cs_foundations',
    code: 'LES-CS-06',
    title: 'Binary Search Trees & Invariants',
    description: 'Binary Search Tree invariant (left < root < right), search, insertion, deletion with in-order predecessor/successor, and skew traps.',
    order: 2,
    estimatedMinutes: 35,
    learningObjectives: [
      'Verify the BST ordering invariant across all subtrees',
      'Perform search and insertion in O(h) time where h is tree height',
      'Handle two-child deletion using in-order successor swapping',
    ],
    conceptIds: ['bst'],
    prerequisiteConceptIds: ['trees'],
  },
  {
    id: 'les_cs_graphs',
    moduleId: 'mod_cs_4',
    domainId: 'cs_foundations',
    code: 'LES-CS-07',
    title: 'Graph Adjacency & Traversal Algorithms',
    description: 'Adjacency matrices vs adjacency lists, Breadth-First Search (queue-based), and Depth-First Search (stack/recursion-based).',
    order: 1,
    estimatedMinutes: 40,
    learningObjectives: [
      'Select between adjacency matrix O(V^2) and list O(V + E) representations',
      'Implement BFS for unweighted shortest path discovery',
      'Implement DFS for cycle detection and connected components',
    ],
    conceptIds: ['graphs'],
    prerequisiteConceptIds: ['queues', 'trees'],
  },
  {
    id: 'les_cs_search',
    moduleId: 'mod_cs_5',
    domainId: 'cs_foundations',
    code: 'LES-CS-08',
    title: 'Binary Search & Logarithmic Bounds',
    description: 'Sorted data prerequisites, mid calculation avoiding overflow (low + (high - low) / 2), and search space halving.',
    order: 1,
    estimatedMinutes: 25,
    learningObjectives: [
      'Explain why sorted data is a mandatory precondition for binary search',
      'Avoid integer overflow bugs in midpoint calculation',
      'Prove the O(log n) worst-case recurrence relation T(n) = T(n/2) + O(1)',
    ],
    conceptIds: ['searching_sorting'],
    prerequisiteConceptIds: ['arrays'],
  },
  {
    id: 'les_cs_hash',
    moduleId: 'mod_cs_5',
    domainId: 'cs_foundations',
    code: 'LES-CS-09',
    title: 'Hash Tables, Collisions & O(1) Maps',
    description: 'Hash functions, uniform hashing assumption, separate chaining vs open addressing, and load factor resizing.',
    order: 2,
    estimatedMinutes: 30,
    learningObjectives: [
      'Design modular hash functions that distribute keys uniformly',
      'Resolve collisions using separate chaining and open addressing (linear probing)',
      'Analyze amortized O(1) lookup versus O(n) worst-case degradation',
    ],
    conceptIds: ['hashing'],
    prerequisiteConceptIds: ['arrays', 'linked_lists'],
  },

  // ==========================================
  // GATE CS LESSONS
  // ==========================================
  {
    id: 'les_gate_toc',
    moduleId: 'mod_gate_1',
    domainId: 'gate_cs',
    code: 'LES-GATE-01',
    title: 'Automata Theory, Regular Languages & Pumping Lemma',
    description: 'DFA 5-tuple, NFA powerset construction, regular language closure properties, and disproving regularity using the Pumping Lemma.',
    order: 1,
    estimatedMinutes: 40,
    learningObjectives: [
      'Convert NFA with epsilon transitions to minimal equivalent DFA',
      'Apply the Pumping Lemma to prove non-regularity of languages like 0^n 1^n',
      'Evaluate language closure under intersection, complementation, and star',
    ],
    conceptIds: ['gate_toc'],
    prerequisiteConceptIds: [],
  },
  {
    id: 'les_gate_compiler',
    moduleId: 'mod_gate_1',
    domainId: 'gate_cs',
    code: 'LES-GATE-02',
    title: 'Context-Free Grammars & Parsing Tables',
    description: 'Top-down LL(1) parsers, FIRST and FOLLOW sets, bottom-up LR(0)/SLR(1)/LALR(1) item sets, and shift-reduce conflicts.',
    order: 2,
    estimatedMinutes: 45,
    learningObjectives: [
      'Compute FIRST and FOLLOW sets for recursive context-free grammars',
      'Detect shift-reduce and reduce-reduce conflicts in parse tables',
      'Differentiate LR(0), SLR(1), LALR(1), and canonical LR(1) power hierarchies',
    ],
    conceptIds: ['gate_compiler'],
    prerequisiteConceptIds: ['gate_toc'],
  },
  {
    id: 'les_gate_os',
    moduleId: 'mod_gate_2',
    domainId: 'gate_cs',
    code: 'LES-GATE-03',
    title: 'Deadlock Invariants & Process Synchronization',
    description: 'Coffman four conditions, Banker algorithm for deadlock avoidance, resource allocation graphs, and semaphore invariants.',
    order: 1,
    estimatedMinutes: 35,
    learningObjectives: [
      'Verify mutual exclusion, hold and wait, no preemption, and circular wait',
      'Execute Banker Algorithm safe state matrix calculations',
      'Detect cycles in resource allocation graphs with single vs multiple instances',
    ],
    conceptIds: ['gate_os'],
    prerequisiteConceptIds: [],
  },
  {
    id: 'les_gate_networks',
    moduleId: 'mod_gate_2',
    domainId: 'gate_cs',
    code: 'LES-GATE-04',
    title: 'Network Protocol Layers & TCP Congestion Control',
    description: 'OSI 7-layer vs TCP/IP model, sliding window protocols, slow start, congestion avoidance, and TCP fast retransmit.',
    order: 2,
    estimatedMinutes: 35,
    learningObjectives: [
      'Calculate throughput and efficiency for Go-Back-N and Selective Repeat',
      'Trace TCP congestion window adjustments during additive increase / multiplicative decrease',
      'Identify subnet masks and CIDR routing prefixes',
    ],
    conceptIds: ['gate_networks'],
    prerequisiteConceptIds: [],
  },
  {
    id: 'les_gate_dbms',
    moduleId: 'mod_gate_3',
    domainId: 'gate_cs',
    code: 'LES-GATE-05',
    title: 'Relational Schema Normalization & BCNF',
    description: 'Functional dependencies, candidate key derivation, 1NF, 2NF, 3NF, Boyce-Codd Normal Form, and lossless decomposition.',
    order: 1,
    estimatedMinutes: 40,
    learningObjectives: [
      'Compute attribute closure X+ and discover all minimal candidate keys',
      'Verify 3NF and BCNF conditions for non-trivial functional dependencies',
      'Perform lossless join and dependency-preserving decomposition',
    ],
    conceptIds: ['gate_dbms'],
    prerequisiteConceptIds: [],
  },

  // ==========================================
  // UPSC CIVIL SERVICES LESSONS
  // ==========================================
  {
    id: 'les_upsc_const',
    moduleId: 'mod_upsc_1',
    domainId: 'upsc_civil',
    code: 'LES-UPSC-01',
    title: 'Constitutional Architecture & The Basic Structure Doctrine',
    description: 'Preamble, quasi-federalism, Article 368 amending procedures, and the Kesavananda Bharati basic structure doctrine.',
    order: 1,
    estimatedMinutes: 45,
    learningObjectives: [
      'Trace the judicial evolution of Article 368 from Shankari Prasad to Kesavananda Bharati',
      'Identify inviolable components of the basic structure of the Constitution',
      'Differentiate simple majority, special majority, and state ratification amendment types',
    ],
    conceptIds: ['upsc_polity_constitution'],
    prerequisiteConceptIds: [],
  },
  {
    id: 'les_upsc_rights',
    moduleId: 'mod_upsc_1',
    domainId: 'upsc_civil',
    code: 'LES-UPSC-02',
    title: 'Fundamental Rights & Constitutional Writs (Articles 14-32)',
    description: 'Equality before law, right to life and personal liberty (Article 21), reasonable restrictions, and writ jurisdictions under Articles 32 and 226.',
    order: 2,
    estimatedMinutes: 40,
    learningObjectives: [
      'Examine the golden triangle of Articles 14, 19, and 21',
      'Distinguish Habeas Corpus, Mandamus, Prohibition, Certiorari, and Quo Warranto writs',
      'Analyze justifiable limitations during national emergencies under Article 358 and 359',
    ],
    conceptIds: ['upsc_fundamental_rights'],
    prerequisiteConceptIds: ['upsc_polity_constitution'],
  },
  {
    id: 'les_upsc_dpsp',
    moduleId: 'mod_upsc_1',
    domainId: 'upsc_civil',
    code: 'LES-UPSC-03',
    title: 'Directive Principles & Fundamental Duties',
    description: 'Part IV socio-economic justice mandates, non-justiciability, Minerva Mills balance, and Part IV-A fundamental civic duties.',
    order: 3,
    estimatedMinutes: 30,
    learningObjectives: [
      'Classify DPSPs into Socialistic, Gandhian, and Liberal-Intellectual categories',
      'Explain the judicial harmony doctrine between Part III (Rights) and Part IV (Principles)',
      'Assess enforcement mechanisms of socio-economic welfare policies',
    ],
    conceptIds: ['upsc_directive_principles'],
    prerequisiteConceptIds: ['upsc_fundamental_rights'],
  },
  {
    id: 'les_upsc_econ',
    moduleId: 'mod_upsc_2',
    domainId: 'upsc_civil',
    code: 'LES-UPSC-04',
    title: 'Macroeconomic Aggregates, Inflation & Fiscal Policy',
    description: 'GDP, GVA, Monetary Policy Committee instruments (Repo, Reverse Repo, CRR), and fiscal deficit management.',
    order: 1,
    estimatedMinutes: 35,
    learningObjectives: [
      'Compute real versus nominal GDP using deflator metrics',
      'Evaluate RBI monetary transmission tools to control demand-pull and cost-push inflation',
      'Analyze budget revenue deficits and capital expenditure multiplier effects',
    ],
    conceptIds: ['upsc_macro_economy'],
    prerequisiteConceptIds: [],
  },
  {
    id: 'les_upsc_env',
    moduleId: 'mod_upsc_2',
    domainId: 'upsc_civil',
    code: 'LES-UPSC-05',
    title: 'Biodiversity Hotspots, Ecology & Climate Treaties',
    description: 'Ecosystem trophic levels, IUCN Red List criteria, Paris Agreement NDCs, and Ramsar wetland conservation.',
    order: 2,
    estimatedMinutes: 35,
    learningObjectives: [
      'Identify UNESCO biosphere reserves and Western Ghats biodiversity hotspots',
      'Explain in-situ versus ex-situ ecological conservation techniques',
      'Analyze international environmental protocols (UNFCCC, CBD, Ramsar)',
    ],
    conceptIds: ['upsc_environment'],
    prerequisiteConceptIds: [],
  },

  // ==========================================
  // GENERAL SCHOOL STEM LESSONS
  // ==========================================
  {
    id: 'les_school_newton',
    moduleId: 'mod_school_1',
    domainId: 'school_stem',
    code: 'LES-STEM-01',
    title: 'Newtonian Dynamics, Inertia & Momentum',
    description: 'The three laws of motion, inertia, momentum conservation, and drawing free-body diagrams for pulley and incline systems.',
    order: 1,
    estimatedMinutes: 30,
    learningObjectives: [
      'State Newton three laws with correct SI unit dimensions',
      'Isolate bodies and construct accurate Free Body Diagrams (FBDs)',
      'Apply conservation of linear momentum to elastic and inelastic collisions',
    ],
    conceptIds: ['school_newton_laws'],
    prerequisiteConceptIds: [],
  },
  {
    id: 'les_school_energy',
    moduleId: 'mod_school_1',
    domainId: 'school_stem',
    code: 'LES-STEM-02',
    title: 'Work, Kinetic Energy & The Work-Energy Theorem',
    description: 'Work done by constant and variable forces, kinetic and potential energy, and conservative vs non-conservative forces.',
    order: 2,
    estimatedMinutes: 30,
    learningObjectives: [
      'Calculate dot-product scalar work W = F · d · cos(theta)',
      'Apply the Work-Energy Theorem: W_net = ΔK',
      'Verify mechanical energy conservation in gravitational fields',
    ],
    conceptIds: ['school_work_energy'],
    prerequisiteConceptIds: ['school_newton_laws'],
  },
  {
    id: 'les_school_table',
    moduleId: 'mod_school_2',
    domainId: 'school_stem',
    code: 'LES-STEM-03',
    title: 'Modern Periodic Table & Electronic Configurations',
    description: 'Moseley modern periodic law, s, p, d, f blocks, atomic radius, ionization enthalpy, and electronegativity trends.',
    order: 1,
    estimatedMinutes: 25,
    learningObjectives: [
      'Predict periodic trends across periods and down groups',
      'Write ground-state electronic configurations using the Aufbau principle',
      'Explain effective nuclear charge and electron shielding effects',
    ],
    conceptIds: ['school_periodic_table'],
    prerequisiteConceptIds: [],
  },
  {
    id: 'les_school_calc',
    moduleId: 'mod_school_2',
    domainId: 'school_stem',
    code: 'LES-STEM-04',
    title: 'Differential Calculus & Tangent Slopes',
    description: 'First principles definition of derivatives, power, product, and quotient rules, and finding local extrema.',
    order: 2,
    estimatedMinutes: 30,
    learningObjectives: [
      'Compute instantaneous rates of change using limits dy/dx = lim h->0 (f(x+h) - f(x))/h',
      'Differentiate algebraic, trigonometric, and exponential functions',
      'Locate critical points and classify local maxima and minima',
    ],
    conceptIds: ['school_calculus_diff'],
    prerequisiteConceptIds: [],
  },
  {
    id: 'les_school_cell',
    moduleId: 'mod_school_2',
    domainId: 'school_stem',
    code: 'LES-STEM-05',
    title: 'Cellular Genetics & Mendelian Inheritance',
    description: 'Mendel laws of segregation and independent assortment, Punnett squares, DNA replication, and monohybrid crosses.',
    order: 3,
    estimatedMinutes: 25,
    learningObjectives: [
      'Construct Punnett squares for dominant and recessive alleles',
      'Calculate phenotypic (3:1) and genotypic (1:2:1) Mendelian ratios',
      'Explain semi-conservative DNA replication and base-pair complementarity',
    ],
    conceptIds: ['school_cell_genetics'],
    prerequisiteConceptIds: [],
  },

  // ==========================================
  // COLLEGE DEGREE LESSONS
  // ==========================================
  {
    id: 'les_college_la',
    moduleId: 'mod_college_1',
    domainId: 'college_eng',
    code: 'LES-ENG-01',
    title: 'Linear Algebra, Eigenvalues & Matrix Decompositions',
    description: 'Vector spaces, span, linear independence, characteristic polynomials, eigenvalues, eigenvectors, and diagonalization.',
    order: 1,
    estimatedMinutes: 40,
    learningObjectives: [
      'Solve det(A - λI) = 0 to extract matrix eigenvalues and eigenvectors',
      'Perform matrix diagonalization A = P D P^(-1) for symmetric matrices',
      'Interpret geometric transformations in n-dimensional Euclidean space',
    ],
    conceptIds: ['college_linear_algebra'],
    prerequisiteConceptIds: [],
  },
  {
    id: 'les_college_ml',
    moduleId: 'mod_college_1',
    domainId: 'college_eng',
    code: 'LES-ENG-02',
    title: 'Machine Learning Optimization & Gradient Descent',
    description: 'Cost function minimization, convex optimization, stochastic gradient descent, learning rate decay, and overfitting regularization.',
    order: 2,
    estimatedMinutes: 40,
    learningObjectives: [
      'Compute partial derivatives and gradient vectors for mean squared error loss',
      'Implement parameter updates θ := θ - α * ∇J(θ)',
      'Apply L1 (Lasso) and L2 (Ridge) regularization to curb model variance',
    ],
    conceptIds: ['college_machine_learning'],
    prerequisiteConceptIds: ['college_linear_algebra'],
  },
  {
    id: 'les_college_dist',
    moduleId: 'mod_college_2',
    domainId: 'college_eng',
    code: 'LES-ENG-03',
    title: 'Distributed Systems, CAP Theorem & Raft Consensus',
    description: 'Consistency, Availability, and Partition tolerance trade-offs, network asynchrony, leader election, and replicated state machines.',
    order: 1,
    estimatedMinutes: 45,
    learningObjectives: [
      'Evaluate strict consistency versus high availability under network partitions',
      'Trace Raft leader election, heartbeats, and log replication phases',
      'Design idempotent APIs for distributed distributed transaction commit',
    ],
    conceptIds: ['college_distributed_sys'],
    prerequisiteConceptIds: [],
  },
];
