import {
  Concept,
  CurriculumDomain,
  DomainId,
  InstitutionStyleGuide,
  Prerequisite,
  Question,
  SystemConfig,
  User,
} from './types.js';

export const DEFAULT_SYSTEM_CONFIG: SystemConfig = {
  masteryThreshold: 0.75,
  challengeThreshold: 0.88,
  prerequisiteThreshold: 0.70,
  forgettingDecayRate: 0.045, // approx 4.5% daily memory decay without spaced retrieval
  uncertaintyThreshold: 0.40,
  interventionThresholdFailures: 3,
  learningRateAlpha: 0.35,
  activeDomainId: 'gate_cs', // Default active domain
  activeInstitutionId: 'iit_madras',
  autoApproveScoreThreshold: 85,
  weights: {
    correctness: 0.45,
    confidence: 0.20,
    difficulty: 0.15,
    responseTime: 0.10,
    independence: 0.10,
  },
  mlConfig: {
    enabled: true,
    weight: 0.30, // 30% ML prediction, 70% Bayesian evidence
    thresholds: {
      weakMax: 0.39,
      developingMax: 0.69,
      strongMax: 0.84,
      masteredMin: 0.85,
    },
  },
  bktConfig: {
    enabled: true,
    weight: 0.25, // 25% BKT Knowledge Tracing, 30% Supervised ML, 45% Bayesian Evidence
    defaultPInit: 0.15,
    defaultPLearn: 0.15,
    defaultPGuess: 0.20,
    defaultPSlip: 0.10,
  },
};

// ==========================================
// CURRICULUM DOMAINS (Multi-Domain Syllabi)
// ==========================================
export const DOMAINS: CurriculumDomain[] = [
  {
    id: 'gate_cs',
    name: 'GATE Exam Syllabus',
    shortLabel: 'GATE CS/IT',
    category: 'Competitive National Exams',
    targetExam: 'Graduate Aptitude Test in Engineering (IISc & IITs)',
    description: 'National competitive entrance exam testing Theory of Computation, Compiler Design, Operating Systems, Database Normalization, and Algorithms.',
    badgeColor: 'bg-amber-900/40 text-amber-300 border-amber-700/50',
    accentColor: '#f59e0b',
    conceptIds: ['gate_toc', 'gate_compiler', 'gate_os', 'gate_dbms', 'gate_networks'],
  },
  {
    id: 'upsc_civil',
    name: 'UPSC Civil Services Exam',
    shortLabel: 'UPSC CSE',
    category: 'Competitive National Exams',
    targetExam: 'Union Public Service Commission (IAS / IPS / IFS)',
    description: 'Indian Administrative Services syllabus covering Constitutional Polity, Judicial Review, Macroeconomics, Modern History, and Biodiversity.',
    badgeColor: 'bg-emerald-900/40 text-emerald-300 border-emerald-700/50',
    accentColor: '#10b981',
    conceptIds: ['upsc_polity_constitution', 'upsc_fundamental_rights', 'upsc_directive_principles', 'upsc_macro_economy', 'upsc_environment'],
  },
  {
    id: 'school_stem',
    name: 'General School Exam Syllabus',
    shortLabel: 'K-12 STEM',
    category: 'Secondary School',
    targetExam: 'CBSE / ICSE / State Board Secondary Exams (Class 10-12)',
    description: 'Foundational secondary school curriculum spanning Newtonian Mechanics, Work & Energy, Chemical Bonding, Differential Calculus, and Genetics.',
    badgeColor: 'bg-sky-900/40 text-sky-300 border-sky-700/50',
    accentColor: '#0ea5e9',
    conceptIds: ['school_newton_laws', 'school_work_energy', 'school_periodic_table', 'school_calculus_diff', 'school_cell_genetics'],
  },
  {
    id: 'college_eng',
    name: 'College Degree Exam Syllabus',
    shortLabel: 'B.Tech / University',
    category: 'University Degree',
    targetExam: 'University Semester Examinations (Computer Science & Engineering)',
    description: 'Higher education engineering degree topics covering Linear Algebra & Eigenvalues, Machine Learning, and Distributed Consensus Protocols.',
    badgeColor: 'bg-purple-900/40 text-purple-300 border-purple-700/50',
    accentColor: '#8b5cf6',
    conceptIds: ['college_linear_algebra', 'college_machine_learning', 'college_distributed_sys'],
  },
  {
    id: 'cs_foundations',
    name: 'CS Data Structures & Algorithms',
    shortLabel: 'CS Foundations',
    category: 'Core Engineering',
    targetExam: 'Technical Coding Interviews & Foundation CS',
    description: 'Standard computer science core spanning contiguous arrays, linked pointer chains, stacks, recursion, binary search trees, and hash tables.',
    badgeColor: 'bg-blue-900/40 text-blue-300 border-blue-700/50',
    accentColor: '#3b82f6',
    conceptIds: ['arrays', 'linked_lists', 'stacks', 'queues', 'recursion', 'trees', 'bst', 'graphs', 'searching_sorting', 'hashing'],
  },
];

// ==========================================
// INSTITUTION-SPECIFIC STYLE GUIDES
// ==========================================
export const INSTITUTIONS: InstitutionStyleGuide[] = [
  {
    id: 'iit_madras',
    name: 'IIT Madras GATE Exam Committee',
    shortCode: 'GATE / IIT',
    badgeColor: 'bg-amber-900/40 text-amber-300 border-amber-700/50',
    description: 'National competitive exam aligned engineering pedagogy emphasizing edge cases, boundary condition traps, and multi-concept synthesis.',
    academicTone: 'EXAM_OPTIMIZED',
    mathNotation: 'FORMAL_ASYMPTOTIC',
    codeStyle: 'STANDARD_C_CPP',
    emphasis: 'Negative marking avoidance, boundary traps, and multi-statement assertion reasoning.',
    guidelines: [
      'Structure questions around numerical values and multi-correct statements.',
      'Test edge cases like empty inputs, integer overflow, and off-by-one indices.',
      'Explicitly state assumptions and formal boundary constraints.',
    ],
  },
  {
    id: 'upsc_commission',
    name: 'UPSC Civil Services Editorial Board',
    shortCode: 'UPSC CSE',
    badgeColor: 'bg-emerald-900/40 text-emerald-300 border-emerald-700/50',
    description: 'Authoritative administrative governance tone emphasizing constitutional articles, supreme court landmark judgments, and socio-economic welfare balance.',
    academicTone: 'INTUITIVE_SOCRATIC',
    mathNotation: 'INFORMAL_BIG_O',
    codeStyle: 'PYTHONIC_CLEAN',
    emphasis: 'Constitutional doctrine of basic structure, judicial precedents, and policy implications.',
    guidelines: [
      'Cite constitutional articles (e.g. Art 14, 21, 32) and landmark judicial rulings.',
      'Use Assertion-Reasoning and Statement 1 & 2 pairing formats characteristic of UPSC Prelims.',
      'Balance economic growth imperatives with sustainable ecological development.',
    ],
  },
  {
    id: 'cbse_board',
    name: 'National School Board & Curriculum',
    shortCode: 'School Board',
    badgeColor: 'bg-sky-900/40 text-sky-300 border-sky-700/50',
    description: 'Clear, foundational K-12 pedagogy emphasizing step-by-step physical intuition, units of measurement, and foundational problem solving.',
    academicTone: 'INTUITIVE_SOCRATIC',
    mathNotation: 'INFORMAL_BIG_O',
    codeStyle: 'PYTHONIC_CLEAN',
    emphasis: 'Everyday physical phenomena, SI unit precision, and diagrammatic reasoning.',
    guidelines: [
      'Begin each explanation with an everyday phenomenon (roller coasters, bicycle gears).',
      'Require explicit SI units (kg, m/s^2, Joules) in physics and chemistry numericals.',
      'Break complex multi-step problems into numbered sub-goals.',
    ],
  },
  {
    id: 'mit_eecs',
    name: 'MIT EECS Formal Academic',
    shortCode: 'MIT 6.006',
    badgeColor: 'bg-red-900/40 text-red-300 border-red-700/50',
    description: 'Mathematically rigorous computer science curriculum emphasizing asymptotic notation (Theta, Big-O, Omega), formal proofs, and invariant analysis.',
    academicTone: 'RIGOROUS_FORMAL',
    mathNotation: 'FORMAL_ASYMPTOTIC',
    codeStyle: 'MODERN_TYPESCRIPT',
    emphasis: 'Formal recurrence relations, structural induction, and asymptotic bounds.',
    guidelines: [
      'State time and space complexity with strict tight bounds (Theta where applicable).',
      'Provide loop invariants and induction premises for recursive correctness.',
      'Analyze worst-case, expected amortized, and best-case performance explicitly.',
    ],
  },
];

// ==========================================
// 1. DATABASE ENTITY: Users
// ==========================================
export const SEED_USERS: User[] = [
  {
    id: 'student_a',
    name: 'Alex Rivera',
    email: 'alex.rivera@masteryflow.edu',
    role: 'STUDENT',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    cohort: 'GATE 2027 Aspirants Cohort',
    institutionId: 'iit_madras',
    activeDomainId: 'gate_cs',
    preferredLanguage: 'en',
    preferredReadingLevel: 'undergraduate',
    dyslexiaModeEnabled: false,
    bionicReadingEnabled: false,
    createdAt: '2026-08-15T09:00:00Z',
    lastActiveAt: '2026-09-28T14:20:00Z',
  },
  {
    id: 'student_b',
    name: 'Blake Chen',
    email: 'blake.chen@masteryflow.edu',
    role: 'STUDENT',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    cohort: 'UPSC Civil Services Foundation',
    institutionId: 'upsc_commission',
    activeDomainId: 'upsc_civil',
    preferredLanguage: 'en',
    preferredReadingLevel: 'high_school',
    dyslexiaModeEnabled: true,
    bionicReadingEnabled: true,
    createdAt: '2026-08-18T11:30:00Z',
    lastActiveAt: '2026-09-28T16:45:00Z',
  },
  {
    id: 'student_c',
    name: 'Maya Patel',
    email: 'maya.patel@masteryflow.edu',
    role: 'STUDENT',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    cohort: 'Class 12 Board STEM & JEE Prep',
    institutionId: 'cbse_board',
    activeDomainId: 'school_stem',
    preferredLanguage: 'hi',
    preferredReadingLevel: 'middle_school',
    dyslexiaModeEnabled: false,
    bionicReadingEnabled: false,
    createdAt: '2026-08-20T14:15:00Z',
    lastActiveAt: '2026-09-28T18:00:00Z',
  },
  {
    id: 'teacher_vance',
    name: 'Prof. Alistair Vance',
    email: 'vance@masteryflow.edu',
    role: 'TEACHER',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    cohort: 'National Academic Examination Board',
    institutionId: 'iit_madras',
    activeDomainId: 'gate_cs',
    preferredLanguage: 'en',
    preferredReadingLevel: 'undergraduate',
    dyslexiaModeEnabled: false,
    bionicReadingEnabled: false,
    createdAt: '2026-07-01T08:00:00Z',
    lastActiveAt: '2026-09-28T19:30:00Z',
  },
];

// ==========================================
// 2. DATABASE ENTITY: Concepts across Multi-Domains
// ==========================================
export const CONCEPTS: Concept[] = [
  // ------------------------------------------
  // DOMAIN 1: GATE CS & ENGINEERING
  // ------------------------------------------
  {
    id: 'gate_toc',
    domainId: 'gate_cs',
    code: 'GATE-CS-01',
    name: 'Theory of Computation & Automata',
    description: 'Deterministic Finite Automata (DFA), NFA equivalence, regular expressions, and the Pumping Lemma.',
    prerequisites: [],
    order: 1,
    category: 'Theoretical Computer Science',
    keyTakeaways: ['DFA vs NFA minimal state equivalence', 'Pumping Lemma proofs for non-regularity', 'Closure properties of regular languages'],
    bloomTarget: 'Analyze',
    audioScript: 'Theory of Computation explores the fundamental limits of what machines can compute. A Deterministic Finite Automaton consists of a finite set of states and deterministic transition rules upon reading input symbols. Regular languages are those accepted by finite automata and can be verified using the Pumping Lemma.',
    readingLevelVariants: {
      middle_school: {
        analogy: 'Think of a turnstile at a train station. It starts locked. If you swipe your card, it unlocks. If you push through, it locks again. It has simple memory states.',
        coreExplanation: 'Automata are tiny step-by-step thinking machines that read symbols from a word one by one to decide if the word follows the rules.',
        realWorldExample: 'A vending machine tracking how many coins you inserted before giving you a snack.',
        keyPoints: ['Finite number of memory states', 'No infinite memory or scratchpad', 'Transitions occur on reading symbols'],
      },
      high_school: {
        analogy: 'A state-diagram flowchart where each input letter directs which arrow you follow next.',
        coreExplanation: 'DFA is a 5-tuple (Q, Sigma, delta, q0, F). The transition function delta maps a state and symbol to exactly one subsequent state.',
        realWorldExample: 'A syntax highlighter in a code editor parsing keywords and numbers.',
        keyPoints: ['DFA requires unique transition for every symbol', 'NFA can transition to multiple states simultaneously', 'Subset construction algorithm converts NFA to DFA'],
      },
      undergraduate: {
        analogy: 'A formal language recognizer with constant O(1) auxiliary state memory.',
        coreExplanation: 'Chomsky Type-3 regular grammars. Pumping lemma states that any string of length >= p can be decomposed as xyz such that |y| > 0 and xy^i z is in L for all i >= 0.',
        realWorldExample: 'Lexical analyzer generator (Lex/Flex) constructing DFA tables from regex tokens.',
        keyPoints: ['Myhill-Nerode theorem and state minimization', 'Closure under union, intersection, complementation', 'Decidability of emptiness and equivalence'],
      },
      executive: {
        analogy: 'Ultra-low latency wire-speed packet inspection finite state engine.',
        coreExplanation: 'Hardware-accelerated regex matching in network intrusion detection systems (Snort/Suricata) compiled directly into silicon FPGA transition tables.',
        realWorldExample: 'DFA-based deep packet inspection filtering malicious payloads at 100 Gbps.',
        keyPoints: ['Linear O(n) scan time independent of pattern count', 'State-space explosion mitigations', 'Aho-Corasick multi-pattern compilation'],
      },
    },
    multilingualVariants: {
      hi: {
        name: 'थ्योरी ऑफ़ कंप्यूटेशन और ऑटोमेटा',
        description: 'DFA, NFA, रेगुलर एक्सप्रेशन और कम्प्यूटेशन की बुनियादी सीमाएं।',
        audioScript: 'थ्योरी ऑफ़ कंप्यूटेशन में हम अध्ययन करते हैं कि कंप्यूटर क्या गणना कर सकते हैं। ऑटोमेटा सीमित मेमोरी वाली ऐसी मशीनें हैं जो इनपुट को पढ़कर निर्णय लेती हैं।',
      },
    },
  },
  {
    id: 'gate_compiler',
    domainId: 'gate_cs',
    code: 'GATE-CS-02',
    name: 'Compiler Design & Parsing',
    description: 'Context-Free Grammars, LL(1) top-down parsing, LR(0)/SLR(1)/LALR(1) bottom-up parsing, and Intermediate Code Generation.',
    prerequisites: ['gate_toc'],
    order: 2,
    category: 'Systems & Software',
    keyTakeaways: ['First and Follow computation', 'Shift-Reduce conflicts in LR parsers', 'Syntax-Directed Translation (SDT)'],
    bloomTarget: 'Evaluate',
  },
  {
    id: 'gate_os',
    domainId: 'gate_cs',
    code: 'GATE-CS-03',
    name: 'Operating Systems & Concurrency',
    description: 'Process scheduling, semaphores, deadlock prevention/detection (Banker algorithm), virtual memory, and page replacement.',
    prerequisites: [],
    order: 3,
    category: 'Systems & Architecture',
    keyTakeaways: ['Critical section mutual exclusion & Peterson algorithm', "Coffman deadlock conditions & Banker's algorithm", 'Belady anomaly in FIFO paging'],
    bloomTarget: 'Analyze',
  },
  {
    id: 'gate_dbms',
    domainId: 'gate_cs',
    code: 'GATE-CS-04',
    name: 'Database Systems & Normalization',
    description: 'Relational algebra, functional dependencies, 1NF to BCNF decomposition, and serializability (conflict vs view).',
    prerequisites: [],
    order: 4,
    category: 'Information Management',
    keyTakeaways: ['Lossless join & dependency preservation', 'BCNF vs 3NF trade-offs', 'Precedence graph testing for conflict serializability'],
    bloomTarget: 'Apply',
  },
  {
    id: 'gate_networks',
    domainId: 'gate_cs',
    code: 'GATE-CS-05',
    name: 'Computer Networks & Protocols',
    description: 'OSI and TCP/IP stack, sliding window protocols (Go-Back-N, Selective Repeat), IPv4 subnetting, and Dijkstra routing.',
    prerequisites: ['gate_os'],
    order: 5,
    category: 'Systems & Networking',
    keyTakeaways: ['Sliding window channel utilization formulas', 'Classless Inter-Domain Routing (CIDR) masks', 'TCP 3-way handshake & congestion control'],
    bloomTarget: 'Evaluate',
  },

  // ------------------------------------------
  // DOMAIN 2: UPSC CIVIL SERVICES EXAM
  // ------------------------------------------
  {
    id: 'upsc_polity_constitution',
    domainId: 'upsc_civil',
    code: 'UPSC-GS2-01',
    name: 'Indian Polity & Constitutional Framework',
    description: 'Evolution of the Indian Constitution, Preamble, Federal structure with unitary tilt, and Citizenship provisions.',
    prerequisites: [],
    order: 1,
    category: 'General Studies II: Governance & Polity',
    keyTakeaways: ['Preamble as non-justiciable soul of Constitution', 'Features borrowed from Government of India Act 1935', 'Sui generis quasi-federal structure'],
    bloomTarget: 'Understand',
    audioScript: 'The Constitution of India is the supreme legal document of the nation. It establishes a sovereign, socialist, secular, democratic republic, securing justice, liberty, equality, and fraternity. The structure combines a rigid constitutional amendment procedure with parliamentary flexibility.',
  },
  {
    id: 'upsc_fundamental_rights',
    domainId: 'upsc_civil',
    code: 'UPSC-GS2-02',
    name: 'Fundamental Rights & Judicial Review',
    description: 'Part III of the Constitution (Articles 12-35), Right to Equality (Art 14), Life & Liberty (Art 21), and Prerogative Writs (Art 32 & 226).',
    prerequisites: ['upsc_polity_constitution'],
    order: 2,
    category: 'General Studies II: Governance & Polity',
    keyTakeaways: ['Golden Triangle: Articles 14, 19, and 21', 'Writs: Habeas Corpus, Mandamus, Prohibition, Certiorari, Quo-Warranto', 'Reasonable restrictions on fundamental freedoms'],
    bloomTarget: 'Analyze',
    audioScript: 'Fundamental Rights in Part III act as a shield against state arbitrariness. The Supreme Court in the Meneka Gandhi case held that procedure established by law under Article 21 must be just, fair, and reasonable, incorporating the American doctrine of substantive due process.',
  },
  {
    id: 'upsc_directive_principles',
    domainId: 'upsc_civil',
    code: 'UPSC-GS2-03',
    name: 'Directive Principles & Basic Structure',
    description: 'Part IV (DPSP), Fundamental Duties (Part IVA), and the Kesavananda Bharati Landmark Basic Structure Doctrine.',
    prerequisites: ['upsc_fundamental_rights'],
    order: 3,
    category: 'General Studies II: Governance & Polity',
    keyTakeaways: ['Harmonious construction between Part III and Part IV', 'Minerva Mills judgment on balance of rights and directives', 'Parliament cannot alter the basic structure under Article 368'],
    bloomTarget: 'Evaluate',
  },
  {
    id: 'upsc_macro_economy',
    domainId: 'upsc_civil',
    code: 'UPSC-GS3-01',
    name: 'Indian Macroeconomy & Monetary Policy',
    description: 'GDP calculation, Inflation targeting (CPI vs WPI), RBI Monetary Policy Committee, fiscal deficit, and Balance of Payments.',
    prerequisites: [],
    order: 4,
    category: 'General Studies III: Economic Development',
    keyTakeaways: ['4% +/- 2% flexible inflation targeting mandate', 'Revenue deficit vs Fiscal deficit vs Primary deficit', 'Current Account Deficit (CAD) drivers'],
    bloomTarget: 'Apply',
  },
  {
    id: 'upsc_environment',
    domainId: 'upsc_civil',
    code: 'UPSC-GS3-02',
    name: 'Biodiversity, Ecology & Climate Treaties',
    description: 'Ecosystem food webs, Wildlife Protection Act 1972, Ramsar Wetlands, UNFCCC Paris Agreement, and National Parks vs Biosphere Reserves.',
    prerequisites: [],
    order: 5,
    category: 'General Studies III: Environment & Ecology',
    keyTakeaways: ['In-situ vs ex-situ conservation', 'IUCN Red List categories and criteria', 'Nationally Determined Contributions (NDCs) under Paris Accord'],
    bloomTarget: 'Analyze',
  },

  // ------------------------------------------
  // DOMAIN 3: GENERAL SCHOOL EXAM SYLLABUS (K-12 STEM)
  // ------------------------------------------
  {
    id: 'school_newton_laws',
    domainId: 'school_stem',
    code: 'STEM-PHY-01',
    name: "Newton's Laws of Motion & Force",
    description: 'Inertia, F = ma equation, action-reaction pairs, momentum conservation, and frictional forces.',
    prerequisites: [],
    order: 1,
    category: 'Physics: Classical Mechanics',
    keyTakeaways: ['First Law defines inertia of rest and motion', 'Second Law: Force equals rate of change of linear momentum', 'Third Law action-reaction act on two different bodies'],
    bloomTarget: 'Understand',
  },
  {
    id: 'school_work_energy',
    domainId: 'school_stem',
    code: 'STEM-PHY-02',
    name: 'Work, Energy and Power',
    description: 'Work done by constant and variable force, Kinetic and Potential energy, and the Law of Conservation of Mechanical Energy.',
    prerequisites: ['school_newton_laws'],
    order: 2,
    category: 'Physics: Classical Mechanics',
    keyTakeaways: ['Work = F * d * cos(theta)', 'Work-Energy Theorem: W_net = Delta K', 'Conservative forces satisfy zero closed-loop work'],
    bloomTarget: 'Apply',
  },
  {
    id: 'school_periodic_table',
    domainId: 'school_stem',
    code: 'STEM-CHEM-01',
    name: 'Periodic Properties & Chemical Bonding',
    description: 'Modern periodic law, atomic radius, electronegativity, ionization enthalpy, and ionic vs covalent bonds.',
    prerequisites: [],
    order: 3,
    category: 'Chemistry: Structure & Bonding',
    keyTakeaways: ['Periodic trends: ionization energy increases across period', 'Octet rule and Lewis dot structures', 'Electronegativity difference dictates bond polarity'],
    bloomTarget: 'Understand',
  },
  {
    id: 'school_calculus_diff',
    domainId: 'school_stem',
    code: 'STEM-MATH-01',
    name: 'Differential Calculus & Rate of Change',
    description: 'Limits, first principles derivative, product/quotient/chain rules, and finding maxima/minima of curves.',
    prerequisites: [],
    order: 4,
    category: 'Mathematics: Analysis',
    keyTakeaways: ['Derivative represents instantaneous tangent slope', 'Product rule: (uv) = u v + u v', 'Stationary points where f(x) = 0 with second derivative test'],
    bloomTarget: 'Apply',
  },
  {
    id: 'school_cell_genetics',
    domainId: 'school_stem',
    code: 'STEM-BIO-01',
    name: 'Cell Division & Mendelian Genetics',
    description: 'Mitosis vs meiosis, DNA structure, monohybrid/dihybrid crosses, and dominant vs recessive alleles.',
    prerequisites: [],
    order: 5,
    category: 'Biology: Cellular & Molecular',
    keyTakeaways: ['Meiosis generates haploid gametes with genetic recombination', 'Mendel 3:1 phenotypic monohybrid ratio', 'Law of Independent Assortment'],
    bloomTarget: 'Analyze',
  },

  // ------------------------------------------
  // DOMAIN 4: COLLEGE DEGREE EXAM SYLLABUS
  // ------------------------------------------
  {
    id: 'college_linear_algebra',
    domainId: 'college_eng',
    code: 'ENG-MATH-201',
    name: 'Linear Algebra, Eigenvalues & SVD',
    description: 'Vector spaces, linear independence, rank-nullity theorem, characteristic polynomials, and Singular Value Decomposition.',
    prerequisites: [],
    order: 1,
    category: 'Engineering Mathematics',
    keyTakeaways: ['A v = lambda v eigenvalue relation', 'Spectral theorem for symmetric matrices', 'SVD decomposes any matrix into U Sigma V^T'],
    bloomTarget: 'Apply',
  },
  {
    id: 'college_machine_learning',
    domainId: 'college_eng',
    code: 'ENG-CS-301',
    name: 'Machine Learning & Optimization',
    description: 'Supervised loss functions, gradient descent, bias-variance tradeoff, regularization (L1/L2), and neural network backpropagation.',
    prerequisites: ['college_linear_algebra'],
    order: 2,
    category: 'Artificial Intelligence',
    keyTakeaways: ['Stochastic Gradient Descent convergence rates', 'L1 Lasso induces sparsity while L2 Ridge shrinks weights', 'Chain rule in computational graphs for backpropagation'],
    bloomTarget: 'Evaluate',
  },
  {
    id: 'college_distributed_sys',
    domainId: 'college_eng',
    code: 'ENG-CS-401',
    name: 'Distributed Systems & Consensus',
    description: 'CAP theorem, logical clocks (Lamport & Vector), two-phase commit, Paxos, and the Raft consensus algorithm.',
    prerequisites: [],
    order: 3,
    category: 'Systems & Infrastructure',
    keyTakeaways: ['CAP theorem: Consistency, Availability, Partition tolerance trade-off', 'Raft leader election and log replication safety', 'Byzantine Fault Tolerance requirements'],
    bloomTarget: 'Create',
  },

  // ------------------------------------------
  // DOMAIN 5: CS FOUNDATIONS & DATA STRUCTURES (Track 4 Original)
  // ------------------------------------------
  {
    id: 'arrays',
    domainId: 'cs_foundations',
    code: 'CS-101',
    name: 'Arrays',
    description: 'Contiguous memory allocation, indexing, cache locality, and dynamic resizing.',
    prerequisites: [],
    order: 1,
    category: 'Sequential Structures',
    keyTakeaways: ['O(1) random access', 'O(n) arbitrary insertion/deletion', 'Contiguous cache lines', 'Amortized doubling strategy'],
    bloomTarget: 'Understand',
  },
  {
    id: 'linked_lists',
    domainId: 'cs_foundations',
    code: 'CS-102',
    name: 'Linked Lists',
    description: 'Node-pointer structures, singly/doubly linked chains, and fast head/tail operations.',
    prerequisites: ['arrays'],
    order: 2,
    category: 'Sequential Structures',
    keyTakeaways: ['Dynamic node allocation', 'O(1) prepend/append with pointers', 'O(n) lookup', 'No cache locality guarantees'],
    bloomTarget: 'Apply',
  },
  {
    id: 'stacks',
    domainId: 'cs_foundations',
    code: 'CS-103',
    name: 'Stacks',
    description: 'LIFO (Last-In First-Out) discipline, function call stacks, and expression evaluation.',
    prerequisites: ['arrays'],
    order: 3,
    category: 'Restricted Structures',
    keyTakeaways: ['LIFO access pattern', 'Constant time push/pop/peek', 'Bracket matching & recursion execution'],
    bloomTarget: 'Apply',
  },
  {
    id: 'queues',
    domainId: 'cs_foundations',
    code: 'CS-104',
    name: 'Queues',
    description: 'FIFO (First-In First-Out) discipline, ring buffers, and scheduling buffers.',
    prerequisites: ['arrays'],
    order: 4,
    category: 'Restricted Structures',
    keyTakeaways: ['FIFO access pattern', 'Circular array or 2-pointer linked implementation', 'BFS & task scheduling'],
    bloomTarget: 'Apply',
  },
  {
    id: 'recursion',
    domainId: 'cs_foundations',
    code: 'CS-105',
    name: 'Recursion',
    description: 'Base cases, recursive call stacks, mathematical induction, and divide-and-conquer.',
    prerequisites: [],
    order: 5,
    category: 'Algorithmic Paradigms',
    keyTakeaways: ['Explicit base case termination', 'Call stack growth', 'Recurrence relations & tree recursion'],
    bloomTarget: 'Analyze',
  },
  {
    id: 'trees',
    domainId: 'cs_foundations',
    code: 'CS-106',
    name: 'Trees',
    description: 'Hierarchical structures, root-child topology, traversals (pre/in/post-order), and depth/height.',
    prerequisites: ['recursion'],
    order: 6,
    category: 'Non-Linear Structures',
    keyTakeaways: ['Hierarchical branching factor', 'O(h) traversal depth', 'Recursive structural definitions'],
    bloomTarget: 'Analyze',
  },
  {
    id: 'bst',
    domainId: 'cs_foundations',
    code: 'CS-107',
    name: 'Binary Search Trees',
    description: 'BST property (left < root < right), search/insert/delete, and tree balance.',
    prerequisites: ['trees'],
    order: 7,
    category: 'Non-Linear Structures',
    keyTakeaways: ['BST invariant', 'O(log n) balanced vs O(n) degenerate', 'In-order traversal yields sorted sequence'],
    bloomTarget: 'Evaluate',
  },
  {
    id: 'graphs',
    domainId: 'cs_foundations',
    code: 'CS-108',
    name: 'Graphs',
    description: 'Vertices and edges, adjacency lists/matrices, BFS, DFS, and cycle detection.',
    prerequisites: ['trees'],
    order: 8,
    category: 'Non-Linear Structures',
    keyTakeaways: ['Adjacency list O(V+E) vs matrix O(V^2)', 'Visited tracking for cycles', 'Topological sort on DAGs'],
    bloomTarget: 'Evaluate',
  },
  {
    id: 'searching_sorting',
    domainId: 'cs_foundations',
    code: 'CS-109',
    name: 'Searching & Sorting',
    description: 'Binary search, merge sort, quick sort, stability, and lower bounds (Omega n log n).',
    prerequisites: ['arrays'],
    order: 9,
    category: 'Algorithmic Paradigms',
    keyTakeaways: ['O(log n) binary search on sorted', 'Comparison sorting Omega(n log n) bound', 'In-place vs out-of-place'],
    bloomTarget: 'Evaluate',
  },
  {
    id: 'hashing',
    domainId: 'cs_foundations',
    code: 'CS-110',
    name: 'Hashing & Hash Tables',
    description: 'Hash functions, collision resolution (chaining, open addressing), load factor, and O(1) average lookup.',
    prerequisites: ['searching_sorting'],
    order: 10,
    category: 'Key-Value Structures',
    keyTakeaways: ['Uniform distribution hash functions', 'Collision resolution techniques', 'Load factor rehashing threshold'],
    bloomTarget: 'Create',
  },
];

// ==========================================
// 3. DATABASE ENTITY: Prerequisites across Domains
// ==========================================
export const SEED_PREREQUISITES: Prerequisite[] = [
  // GATE CS
  {
    id: 'prereq_gate_toc_compiler',
    domainId: 'gate_cs',
    conceptId: 'gate_compiler',
    prerequisiteConceptId: 'gate_toc',
    requiredThreshold: 0.70,
    dependencyStrength: 'CRITICAL',
    rationale: 'Parsing in compilers directly requires fluency with Context-Free Grammars and pushdown automata.',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'prereq_gate_os_networks',
    domainId: 'gate_cs',
    conceptId: 'gate_networks',
    prerequisiteConceptId: 'gate_os',
    requiredThreshold: 0.70,
    dependencyStrength: 'RECOMMENDED',
    rationale: 'Network socket communication and protocol concurrency build on operating system process IPC.',
    createdAt: '2026-08-01T00:00:00Z',
  },

  // UPSC Civil Services
  {
    id: 'prereq_upsc_polity_rights',
    domainId: 'upsc_civil',
    conceptId: 'upsc_fundamental_rights',
    prerequisiteConceptId: 'upsc_polity_constitution',
    requiredThreshold: 0.70,
    dependencyStrength: 'CRITICAL',
    rationale: 'Understanding the philosophy of the Preamble is a strict prerequisite before examining Fundamental Rights.',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'prereq_upsc_rights_dpsp',
    domainId: 'upsc_civil',
    conceptId: 'upsc_directive_principles',
    prerequisiteConceptId: 'upsc_fundamental_rights',
    requiredThreshold: 0.70,
    dependencyStrength: 'CRITICAL',
    rationale: 'The balance between Part III (Fundamental Rights) and Part IV (DPSP) is key to the Basic Structure Doctrine.',
    createdAt: '2026-08-01T00:00:00Z',
  },

  // General School STEM
  {
    id: 'prereq_school_newton_work',
    domainId: 'school_stem',
    conceptId: 'school_work_energy',
    prerequisiteConceptId: 'school_newton_laws',
    requiredThreshold: 0.70,
    dependencyStrength: 'CRITICAL',
    rationale: 'Work calculations and kinetic energy derivation require understanding Newton second law (F = ma).',
    createdAt: '2026-08-01T00:00:00Z',
  },

  // College Degree
  {
    id: 'prereq_college_linalg_ml',
    domainId: 'college_eng',
    conceptId: 'college_machine_learning',
    prerequisiteConceptId: 'college_linear_algebra',
    requiredThreshold: 0.70,
    dependencyStrength: 'CRITICAL',
    rationale: 'Matrix vector products, projections, and eigenvalues are mandatory to understand PCA and neural weights.',
    createdAt: '2026-08-01T00:00:00Z',
  },

  // CS Foundations
  {
    id: 'prereq_arr_ll',
    domainId: 'cs_foundations',
    conceptId: 'linked_lists',
    prerequisiteConceptId: 'arrays',
    requiredThreshold: 0.70,
    dependencyStrength: 'CRITICAL',
    rationale: 'Learners must understand sequential memory allocation in arrays to contrast node pointer tradeoffs.',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'prereq_arr_stk',
    domainId: 'cs_foundations',
    conceptId: 'stacks',
    prerequisiteConceptId: 'arrays',
    requiredThreshold: 0.70,
    dependencyStrength: 'CRITICAL',
    rationale: 'Stack push/pop operations require array capacity doubling or linked node understanding.',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'prereq_arr_que',
    domainId: 'cs_foundations',
    conceptId: 'queues',
    prerequisiteConceptId: 'arrays',
    requiredThreshold: 0.70,
    dependencyStrength: 'CRITICAL',
    rationale: 'Queues require circular array modulo arithmetic or head/tail pointer tracking.',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'prereq_rec_trees',
    domainId: 'cs_foundations',
    conceptId: 'trees',
    prerequisiteConceptId: 'recursion',
    requiredThreshold: 0.70,
    dependencyStrength: 'CRITICAL',
    rationale: 'Tree traversals and divide-and-conquer subproblem breakdowns require recursive fluency.',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'prereq_trees_bst',
    domainId: 'cs_foundations',
    conceptId: 'bst',
    prerequisiteConceptId: 'trees',
    requiredThreshold: 0.70,
    dependencyStrength: 'CRITICAL',
    rationale: 'BST invariant builds directly on general binary tree topology.',
    createdAt: '2026-08-01T00:00:00Z',
  },
];

// ==========================================
// 4. DATABASE ENTITY: Questions across Multi-Domains
// ==========================================
export const QUESTIONS: Question[] = [
  // ------------------------------------------
  // GATE CS QUESTIONS
  // ------------------------------------------
  {
    id: 'q_gate_toc_1',
    domainId: 'gate_cs',
    conceptId: 'gate_toc',
    questionText: 'Which of the following statements is TRUE regarding regular languages and Deterministic Finite Automata (DFA)?',
    questionType: 'Understanding',
    questionFormat: 'MCQ',
    difficulty: 'medium',
    bloomLevel: 'Analyze',
    options: [
      'Every NFA can be converted to an equivalent DFA with at most 2^n states.',
      'The set of all non-empty languages is accepted by a 1-state DFA.',
      'Regular languages are NOT closed under complementation.',
      'Determining whether a DFA accepts an infinite language is undecidable.',
    ],
    correctOptionIndex: 0,
    explanation: 'By the subset construction (powerset construction) theorem, an NFA with n states has an equivalent DFA with at most 2^n states.',
    hint: 'Think about the subset construction theorem converting non-deterministic states to powersets.',
    expectedTimeSeconds: 40,
    isDiagnostic: true,
    institutionStyleId: 'iit_madras',
    evaluationStatus: 'APPROVED',
  },
  {
    id: 'q_gate_os_deadlock',
    domainId: 'gate_cs',
    conceptId: 'gate_os',
    questionText: "In an operating system with 3 processes sharing 4 identical units of a resource, what is the maximum request each process can make such that deadlock NEVER occurs?",
    questionType: 'Application',
    questionFormat: 'NUMERICAL_ANALYSIS',
    difficulty: 'hard',
    bloomLevel: 'Evaluate',
    options: [
      'Each process can request at most 2 units (Formula: Sum(Max_i) < R + N)',
      'Each process can request at most 3 units',
      'Each process can request at most 4 units',
      'Each process can request at most 1 unit',
    ],
    correctOptionIndex: 0,
    explanation: "For N=3 processes and R=4 resources, deadlock-free condition requires Sum(Max_i) < R + N = 4 + 3 = 7. If each process demands k units, 3k <= 6, thus k <= 2.",
    hint: 'Use the safe condition: Total resources must exceed the sum of maximum demands minus N.',
    expectedTimeSeconds: 45,
    institutionStyleId: 'iit_madras',
    evaluationStatus: 'APPROVED',
  },
  {
    id: 'q_gate_dbms_bcnf',
    domainId: 'gate_cs',
    conceptId: 'gate_dbms',
    questionText: 'Given relation R(A, B, C, D) with functional dependencies {A -> B, B -> C, C -> D}. What is the highest normal form of R?',
    questionType: 'Application',
    questionFormat: 'MCQ',
    difficulty: 'medium',
    bloomLevel: 'Analyze',
    options: [
      '1NF only (Transitive and partial dependencies exist for key A)',
      '2NF (Prime attributes determine non-prime attributes)',
      '3NF (No transitive dependency exists)',
      'BCNF (Every determinant is a candidate key)',
    ],
    correctOptionIndex: 0,
    explanation: 'Candidate key is A. Functional dependency B -> C has non-prime attribute C determined by non-superkey B, which violates 3NF and 2NF (transitive dependency). Highest is 1NF.',
    hint: 'Find the candidate key first. Is B a superkey?',
    expectedTimeSeconds: 35,
    institutionStyleId: 'iit_madras',
    evaluationStatus: 'APPROVED',
  },

  // ------------------------------------------
  // UPSC CIVIL SERVICES QUESTIONS
  // ------------------------------------------
  {
    id: 'q_upsc_polity_basic_structure',
    domainId: 'upsc_civil',
    conceptId: 'upsc_directive_principles',
    questionText: 'Consider the following statements regarding the Basic Structure Doctrine in Indian Constitutional Law:\n\n1. It was propounded by the Supreme Court in the Kesavananda Bharati case (1973).\n2. Article 368 explicitly defines the components of the basic structure.\n\nWhich of the statements given above is/are correct?',
    questionType: 'Understanding',
    questionFormat: 'ASSERTION_REASON',
    difficulty: 'medium',
    bloomLevel: 'Analyze',
    options: [
      '1 only',
      '2 only',
      'Both 1 and 2',
      'Neither 1 nor 2',
    ],
    correctOptionIndex: 0,
    explanation: 'Statement 1 is correct: Propounded in Kesavananda Bharati v. State of Kerala (1973). Statement 2 is incorrect: The Constitution does NOT define basic structure anywhere; it is a judicially innovated concept evolved on a case-by-case basis.',
    hint: 'Does the text of Article 368 mention the word "Basic Structure" anywhere?',
    expectedTimeSeconds: 35,
    isDiagnostic: true,
    institutionStyleId: 'upsc_commission',
    evaluationStatus: 'APPROVED',
  },
  {
    id: 'q_upsc_macro_rbi',
    domainId: 'upsc_civil',
    conceptId: 'upsc_macro_economy',
    questionText: 'When the Reserve Bank of India (RBI) conducts Open Market Operations (OMO) by purchasing Government Securities from commercial banks, what is the immediate economic impact?',
    questionType: 'Application',
    questionFormat: 'MCQ',
    difficulty: 'medium',
    bloomLevel: 'Evaluate',
    options: [
      'Increases liquidity in the banking system and reduces short-term interest rates',
      'Decreases the money supply in the market and raises bond yields',
      'Directly increases the central government fiscal deficit',
      'Appreciates the rupee against the US dollar instantly',
    ],
    correctOptionIndex: 0,
    explanation: 'When RBI purchases securities, it injects rupee liquidity into commercial banks reserves, expanding credit availability and softening borrowing rates.',
    hint: 'Think about cash flow: Does cash leave the RBI into the banking system, or does it leave the banks into the RBI?',
    expectedTimeSeconds: 30,
    institutionStyleId: 'upsc_commission',
    evaluationStatus: 'APPROVED',
  },

  // ------------------------------------------
  // GENERAL SCHOOL STEM QUESTIONS
  // ------------------------------------------
  {
    id: 'q_school_newton_calc',
    domainId: 'school_stem',
    conceptId: 'school_newton_laws',
    questionText: 'A toy car of mass 2.0 kg accelerates from rest to 6.0 m/s in 3.0 seconds under a constant horizontal force. What is the magnitude of the net force acting on the car?',
    questionType: 'Application',
    questionFormat: 'NUMERICAL_ANALYSIS',
    difficulty: 'easy',
    bloomLevel: 'Apply',
    options: [
      '4.0 N (Acceleration a = 2.0 m/s^2, Force F = m * a = 4.0 N)',
      '6.0 N',
      '12.0 N',
      '2.0 N',
    ],
    correctOptionIndex: 0,
    explanation: 'Acceleration a = (v - u)/t = (6.0 - 0)/3.0 = 2.0 m/s^2. By Newton Second Law: F = m * a = 2.0 kg * 2.0 m/s^2 = 4.0 N.',
    hint: 'First find the acceleration using (final velocity - initial velocity) / time, then multiply by mass.',
    expectedTimeSeconds: 25,
    isDiagnostic: true,
    institutionStyleId: 'cbse_board',
    evaluationStatus: 'APPROVED',
  },
  {
    id: 'q_school_chem_bond',
    domainId: 'school_stem',
    conceptId: 'school_periodic_table',
    questionText: 'Why does Sodium (Na, atomic number 11) readily combine with Chlorine (Cl, atomic number 17) to form an ionic crystal lattice?',
    questionType: 'Understanding',
    questionFormat: 'MCQ',
    difficulty: 'easy',
    bloomLevel: 'Understand',
    options: [
      'Sodium transfers 1 valence electron to Chlorine so both achieve stable noble gas octets',
      'Sodium and Chlorine share 2 pairs of electrons through a covalent double bond',
      'Both elements have identical high electronegativities',
      'Chlorine loses an electron to become an anion',
    ],
    correctOptionIndex: 0,
    explanation: 'Sodium ([Ne] 3s1) readily loses 1 electron to become Na+, while Chlorine ([Ne] 3s2 3p5) gains 1 electron to become Cl-, achieving stable noble gas configurations held by electrostatic attraction.',
    hint: 'Look at the outer valence shell: How many electrons do they need to lose or gain to achieve 8?',
    expectedTimeSeconds: 20,
    institutionStyleId: 'cbse_board',
    evaluationStatus: 'APPROVED',
  },

  // ------------------------------------------
  // COLLEGE DEGREE QUESTIONS
  // ------------------------------------------
  {
    id: 'q_college_linalg_eigen',
    domainId: 'college_eng',
    conceptId: 'college_linear_algebra',
    questionText: 'If a 2x2 matrix has eigenvalues lambda_1 = 3 and lambda_2 = 5, what are the determinant and trace of the matrix?',
    questionType: 'Application',
    questionFormat: 'MCQ',
    difficulty: 'medium',
    bloomLevel: 'Apply',
    options: [
      'Determinant = 15, Trace = 8',
      'Determinant = 8, Trace = 15',
      'Determinant = 15, Trace = 2',
      'Determinant = 3, Trace = 5',
    ],
    correctOptionIndex: 0,
    explanation: 'By fundamental linear algebra theorems: Determinant is the product of eigenvalues (3 * 5 = 15), and Trace is the sum of eigenvalues (3 + 5 = 8).',
    hint: 'Determinant is the product of eigenvalues; trace is the sum.',
    expectedTimeSeconds: 25,
    isDiagnostic: true,
    institutionStyleId: 'mit_eecs',
    evaluationStatus: 'APPROVED',
  },
  {
    id: 'q_college_ml_overfit',
    domainId: 'college_eng',
    conceptId: 'college_machine_learning',
    questionText: 'A deep neural network exhibits 99.8% training accuracy but only 64.2% test validation accuracy. Which intervention is most appropriate to mitigate this variance?',
    questionType: 'Transfer',
    questionFormat: 'MCQ',
    difficulty: 'hard',
    bloomLevel: 'Evaluate',
    options: [
      'Apply L2 weight decay regularization and dropout to penalize excessive model complexity',
      'Increase the number of hidden layers and training epochs',
      'Remove all validation data and train exclusively on the combined set',
      'Decrease dataset size to reduce noise',
    ],
    correctOptionIndex: 0,
    explanation: 'High training accuracy paired with poor test accuracy indicates high variance (overfitting). Regularization (L2 weight decay, dropout, data augmentation) constrains hypothesis space to improve generalization.',
    hint: 'The model has memorized the training set. How do you constrain its complexity?',
    expectedTimeSeconds: 30,
    institutionStyleId: 'mit_eecs',
    evaluationStatus: 'APPROVED',
  },

  // ------------------------------------------
  // CS FOUNDATIONS QUESTIONS (Track 4 Original)
  // ------------------------------------------
  {
    id: 'q_arr_1',
    domainId: 'cs_foundations',
    conceptId: 'arrays',
    questionText: 'What is the theoretical time complexity of accessing an element in an array at a given index i?',
    questionType: 'Recall',
    questionFormat: 'MCQ',
    difficulty: 'easy',
    bloomLevel: 'Remember',
    options: ['O(n)', 'O(1)', 'O(log n)', 'O(i)'],
    correctOptionIndex: 1,
    explanation: 'Arrays allocate contiguous memory blocks, allowing the CPU to compute the exact memory address in O(1) time via base_address + (i * element_size).',
    hint: 'Think about pointer arithmetic: can the hardware calculate the address immediately without scanning?',
    expectedTimeSeconds: 15,
    isDiagnostic: true,
    institutionStyleId: 'mit_eecs',
    evaluationStatus: 'APPROVED',
  },
  {
    id: 'q_arr_code_output',
    domainId: 'cs_foundations',
    conceptId: 'arrays',
    questionText: 'Predict the console output of this dynamic array resizing snippet:',
    questionType: 'Application',
    questionFormat: 'CODE_OUTPUT',
    difficulty: 'medium',
    bloomLevel: 'Apply',
    codeSnippet: `const numbers = [10, 20, 30];
numbers.push(40);
const removed = numbers.shift();
numbers.push(removed + 5);
console.log(numbers.length + ":" + numbers[numbers.length - 1]);`,
    expectedOutput: '4:15',
    options: ['4:15', '3:15', '4:40', '3:35'],
    correctOptionIndex: 0,
    explanation: 'Initially [10, 20, 30]. push(40) makes it [10, 20, 30, 40]. shift() removes 10, leaving [20, 30, 40]. push(10 + 5 = 15) results in [20, 30, 40, 15]. Length is 4 and last element is 15.',
    hint: 'Track the array step-by-step: push appends to the end, while shift removes from the beginning.',
    expectedTimeSeconds: 30,
    institutionStyleId: 'mit_eecs',
    evaluationStatus: 'APPROVED',
  },
  {
    id: 'q_ll_fill_blank',
    domainId: 'cs_foundations',
    conceptId: 'linked_lists',
    questionText: 'Fill in the missing critical line to insert a new node at the head of a singly linked list without losing the rest of the chain:',
    questionType: 'Application',
    questionFormat: 'FILL_BLANK',
    difficulty: 'medium',
    bloomLevel: 'Apply',
    fillBlankTemplate: `function insertAtHead(head: ListNode | null, val: number): ListNode {
  const newNode = new ListNode(val);
  // >>> INSERT MISSING LINE HERE <<<
  head = newNode;
  return head;
}`,
    fillBlankSolution: 'newNode.next = head;',
    options: [
      'newNode.next = head;',
      'head.next = newNode;',
      'newNode.next = null;',
      'head = newNode.next;',
    ],
    correctOptionIndex: 0,
    explanation: 'You must first connect newNode.next to point to the current head before redirecting head to newNode. If you assign head = newNode first, you orphan the existing list!',
    hint: 'If you point head to newNode first, what happens to the memory address of the old chain?',
    expectedTimeSeconds: 25,
    institutionStyleId: 'mit_eecs',
    evaluationStatus: 'APPROVED',
  },
];
